name: CI - Build, and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Replace with your preferred runner

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust based on your project's requirements

      - name: Install dependencies
        run: yarn install  # Or yarn install, depending on your project setup

      - name: Build Next.js app
        run: yarn build  # Or yarn build

